### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by jpgif** [HaikuTeam/animator#1045]
Hi everyone, is there a version with a ready to install executable file?
I cannot make it run on my Win10 machine
Thank you

**Comment by serbuk** [comment]
Hi, having the same problem. Even "unzip to folder" option would be really helpful (if it is ever possible).
Thank you

**Comment by gumptious** [comment]
Thank you for reporting. Closing in favor of https://github.com/HaikuTeam/animator/issues/1050 where there's more progress towards a solution.
