### ISSUE TITLE
yurn start error

### ISSUE THREAD

**Issue by amirX01** [HaikuTeam/animator#1051]
i got this error i read the link but i could not solve my problem
![Screenshot from 2021-09-30 14-29-29](https://user-images.githubusercontent.com/36998408/135443559-93d5f7d6-4d58-4f5d-928d-74175a72ac65.png)

**Comment by partytax** [comment]
What distribution are you running? If you're on a Debian-based distro, try `apt install libgconf-2-4`. 

Did you use my instructions in [https://github.com/HaikuTeam/animator/pull/1048/files](https://github.com/HaikuTeam/animator/pull/1048/files) ? If not, might want to install the other dependencies listed there before running `yarn go` again.

**Comment by amirX01** [comment]
thank you so much it works
