### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by icc-guerrero** [HaikuTeam/animator#1067]
I've realised that all links to the documentation within the app and also in the web site points to haiku.ai site, which is down. Is there any way to access to the documentation now?

**Comment by gumptious** [comment]
There are two sources of docs: 

The **help articles**, focused on FAQs and use-case questions. Formerly help.haikuforteams.com / help.haiku.ai. This content was managed through a paid service. The exported data can be found here: https://github.com/HaikuTeam/animator/tree/master/articles

The **reference docs**, focused on API and functional documentation. Formerly docs.haikuforteams.com / docs.haiku.ai. This content was compiled with Gitbook and self-hosted; the source is available here: https://github.com/HaikuTeam/docs
