### ISSUE TITLE
yarn or baggage of errors !

### ISSUE THREAD

**Issue by baltao1** [HaikuTeam/animator#1069]
- [ ? ] I kindly request all developers with skills higher than noobs to create a .exe file for Windows as i am unable to do so after various retries. Sigh! Anyone there?

**Comment by baltao1** [comment]
GitHub is dark and empty it seems lol.

**Comment by megaarmos** [comment]
> * [ ? ] I kindly request all developers with skills higher than noobs to create a .exe file for Windows as i am unable to do so after various retries. Sigh! Anyone there?

I also tried several times to follow the instructions but it was too hard

**Comment by drucinsky** [comment]
I can't  too run this app on Windows. I do all readme but i have problem with node-gyp and nodegit.. When i install Ubuntu on VirtualMachine i can easy install it on linux and be can generate lottie file? Any know?
