### ISSUE TITLE
Where is the "next release"? We want the Windows binary, please! 😢

### ISSUE THREAD

**Issue by JacobHornbeck** [HaikuTeam/animator#1101]
@roperzh and @zackbrown (I am pinging you directly because it says you are part of Haiku and have worked on this project)

In the [5.1.2 release (Sep 19, 2021)](https://github.com/HaikuTeam/animator/releases/tag/5.1.2), it says:

> Windows users: the next release should include a pre-built Windows binary

It is now Feb 17, 2023, and there is no "next release". Will this happen? Or is Animator by Haiku no longer supported?

I tried following the instructions in the README file, but I was getting a bunch of errors and was not able to get it to work.

**Comment by cxumol** [comment]
Their whole team seems disappeared. You may want to try https://glaxnimate.mattbas.org/ instead.

**Comment by TheFireBrand** [comment]
I found something that might be much better than Haiku.. 
I've not tried it yet, though.. 
If you do, please get back to me.. 

Check out Theatre.js
It's actually for animating Three.js scenes, but they've cleverly included the ability to work with HTML/CSS/SVG..

#marketopportunityrighthere

**Comment by JacobHornbeck** [comment]
@TheFireBrand That will not work for my need. I am wanting to make a Lottie animation for my apps splash screen. So for me @cxumol gave the perfect solution (though I really wish Animator by Haiku would work, since the screenshots make it look like a very clean UI)

**Comment by JacobHornbeck** [comment]
An update on [Glaxnimate](https://glaxnimate.mattbas.org/).
It does have the features and options I need, but it is quite confusing in some aspects. The user manual on their website is a little confusing as well, and there is no search (or at least I couldn't find any), which makes it even harder to find what is needed.
