### ISSUE TITLE
New elements not showing up in timeline panel

### ISSUE THREAD

**Issue by taylorpoe** [HaikuTeam/animator#4]
Summary:
I've added a new element to the stage. It shows up on the stage, but not in the timeline panel. Exiting the project and rerentering & opening and closing haiku do not resolve the issue. 

Steps to reproduce:
Not sure. This project has been open for a long time. I've made hundreds of changes to it. Previous to this issue, I had noticed that one of my changes was not reflected upon publish and I reviewed in Creator and saw that the change had undone itself (reverted). My hunch is that the whole project is somehow corrupted, although I can make changes and publish new changes. I simply cannot add new elements and interact with them on the timeline.

Screenshots, logs, etc:
https://cl.ly/1h0u0J2X1B0f

**Comment by tsortwehttam** [comment]
<img width="1173" alt="screen shot 2017-05-17 at 2 36 10 pm" src="https://cloud.githubusercontent.com/assets/573480/26170110/3e804ee8-3b0e-11e7-95b1-41634fb9459b.png">

Apparently this happens if > 10 elements are instantiated.

**Comment by taylorpoe** [comment]
Creator not feeling the luv w those hearts. 🥁

**Comment by tsortwehttam** [comment]
Of note, it appears that instantiation succeeds everywhere, it just doesn't _display_ in the timeline. For example, master correctly registers the diff of the new instance in the bytecode:

<img width="832" alt="screen shot 2017-05-17 at 2 40 44 pm" src="https://cloud.githubusercontent.com/assets/573480/26170294/f0032f8c-3b0e-11e7-97e6-8a0453dce67d.png">

**Comment by tsortwehttam** [comment]
Bitten by a stupid string hack. Fix will roll out with version 2.0.77.
