### ISSUE TITLE
"cannot find npm" happens on publish intermittently, inconsistently

### ISSUE THREAD

**Issue by tsortwehttam** [HaikuTeam/animator#6]
Summary: Occasionally the publish step fails with "Cannot find NPM - is it in your PATH?" issue. This originates from `enpeem` which ultimately shells out to the npm CLI. However, this doesn't happen with any regularity on (a) mono, (b) locally built distro. It seems specifically to occur when the distro is launched after downloading.

Steps to reproduce: ???

Release version, system info, etc: Since 2.0.68 or so?

**Comment by tsortwehttam** [comment]
It happens consistently for me when I attempt to launch Haiku 2.0.80 which I have downloaded to my Desktop.

**Comment by zackbrown** [comment]
related?  https://www.npmjs.com/package/shell-path

**Comment by zackbrown** [comment]
^ seems like that may be the key.  fits with the pieces you described, that standalone macOS apps don't inherit $PATH, but a dev version or possibly a locally built version do

**Comment by tsortwehttam** [comment]
But the locally built version is the one that gets uploaded ... 😭

**Comment by zackbrown** [comment]
alternatively, bundling a specific version of npm with the app (a la `require('npm')`) would be more robust; reduces surface area of weird user issues like "I don't have npm installed" or "I have a really old or incompatible version fo npm installed"

**Comment by zackbrown** [comment]
hm, maybe it's a quirk about it running on your own machine...?  or from a directory that's not /Applications ?  or running it from CLI instead of double-clicking? [of note: @taylorpoe was running into this issue when he double-clicked to start the app, but it went away when he ran it from the CLI]

**Comment by zackbrown** [comment]
@matthewtoast  when it *works* for you, have you been running as a double-clicked app or running from terminal (ostensibly to see logs) ?  seems very likely to me that the $PATH-not-being-inherited-by-vanilla-run-apps is the cause here, and it makes sense that $PATH would be inherited when the app is opened via terminal.

**Comment by zackbrown** [comment]
Also:  this is showstopper priority, as it will block users from publishing

**Comment by tsortwehttam** [comment]
Yeah, that makes a lot of sense. I'm testing out using `require('npm')` directly now.

**Comment by zackbrown** [comment]
👍

**Comment by tsortwehttam** [comment]
Initial test seems to indicate that require('npm') resolves this. I've gone through the process of opening creator, opening a project, making a change, and publishing three times (once on mono; once on staging build launched via double-click; once on production build launched via double-click; and each time it seems to work). Version 2.0.81 has this change: https://s3.amazonaws.com/haiku-electron-releases-production/releases/production-master-mac-latest.zip

**Comment by zackbrown** [comment]
👏
