### ISSUE TITLE
Adding non-Sketch files to Library appears to be broken

### ISSUE THREAD

**Issue by taylorpoe** [HaikuTeam/animator#7]
Summary:
Image files added directly to the Library are not showing up.

Steps to reproduce:
Click 'import' in Library pane. Add .png file. Wait. File does not show up in Library.

Screenshots, logs, etc:
No errors on any of the three consoles.

Seems like the call is being made:
```[plumbing] subproc #3 master in /Users/taylorpoe/.haiku/projects/taylor/NewDashProto is {}
[master] /Users/taylorpoe/.haiku/projects/taylor/NewDashProto websocket is 1
2017-05-22T22:03:49.806Z - info: Plumbing got method call: linkAsset 0=/Users/taylorpoe/Desktop/Other badges.png, 1=/Users/taylorpoe/.haiku/projects/taylor/NewDashProto
[master] calling linkAsset [ '/Users/taylorpoe/Desktop/Other badges.png' ]
File did read: designs/Other badges.png 225829
File upserted: designs/Other badges.png
2017-05-22T22:03:50.305Z - info: [master] File changed: /Users/taylorpoe/.haiku/projects/taylor/NewDashProto/designs/Other badges.png
File did read: designs/Other badges.png 225829
File upserted: designs/Other badges.png
2017-05-22T22:03:50.382Z - info: [master] File ingested: /Users/taylorpoe/.haiku/projects/taylor/NewDashProto/designs/Other badges.png
[master] calling doesProjectHaveUnsavedChanges []
```

Release version, system info, etc:
Prod 2.0.82 & Dev 2.0.86

Account, project info, etc:
"/Users/taylorpoe/.haiku/projects/taylor/NewDashProto"

**Comment by tsortwehttam** [comment]
So, we don't yet officially support png/jpb/gif and other bitmap files. And in fact, we filter out any file from the library that has a file type that we "don't know how" to instantiate. In other words, we only support .svg and .sketch in the library. Since there is an open feature request in Trello indicating the desire to support bitmap images, I'm going to close this as an issue here.

**Comment by tsortwehttam** [comment]
Trello card: https://trello.com/c/6VZBptyr/84-bitmap-image-formats-jpg-png-etc
