### ISSUE TITLE
No effect from animations

### ISSUE THREAD

**Issue by taylorpoe** [HaikuTeam/animator#9]
On Taylor Org (taylor+taylor@haiku.ai supersecure) the project "moutainsillo" has animations that aren't affecting the final product on stage or publish. If you go to frame 90 you'll see that there are animations on the "star" elements. Scubbing the timeline accurately shows the scaling being tweened in the input fields (the numbers change), but as you will see — no effect on the elements on the stage. (The stars ought to scale, spin and opacitate based on what the timeline dictates.)

These animations were all working as designed until I dragged all of the star segments' forward in time to make them start sooner than they had previously. After doing this, they broke. I imagine somehow there's an error that can happen because of this dragging. Does anything look off in the bytecode?

Example star element:
```
"haiku:bee146007b17": {
        viewBox: { "0": { value: "0 0 11 11" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 11 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 11 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 300.5, edited: true } },
        "translation.y": { "0": { value: 181, edited: true } },
        "style.zIndex": { "0": { value: 9 } },
        opacity: {
          "0": { value: 0.7, edited: true },
          "2083": { value: 0.7, edited: true, curve: "linear" },
          "2300": { value: 1, edited: true, curve: "linear" },
          "2667": { value: 0.7, edited: true }
        },
        "scale.x": {
          "0": { value: 1 },
          "2083": { value: 1, edited: true, curve: "easeInOutCubic" },
          "2300": { value: 2, edited: true, curve: "easeInOutCubic" },
          "2667": { value: 1, edited: true }
        },
        "scale.y": {
          "0": { value: 1 },
          "2083": { value: 1, edited: true, curve: "easeOutCubic" },
          "2300": { value: 2, edited: true, curve: "easeInOutCubic" },
          "2667": { value: 1, edited: true }
        },
        "rotation.z": {
          "0": { value: 0 },
          "2083": { value: 0, edited: true, curve: "easeInOutCirc" },
          "2667": { edited: true }
        }
      },
```

**Comment by zackbrown** [comment]
to double-check:  you've tried restarting Haiku [full quit and restart, not just cmd+r] and seeing if the animations work?  also which version are you using?  (and dev/staging/prod?)

**Comment by taylorpoe** [comment]
Yes, quit/reopened several times. Issue is present on dev 2.0.110 and production 2.0.107

**Comment by tsortwehttam** [comment]
For one thing, it looks like `rotation.z` didn't get set with a value for some reason, so it is `NaN`. Not sure why the scaling isn't happening, though.

**Comment by tsortwehttam** [comment]
So I can try to reproduce the root cause (bad values getting written), can you explain exactly what you did before the issue?

- How much timeline zoom did you have?
- How fast did you drag the segment? Did you drag from its body or an edge?
- Any error in the script console or among the toasts?
- How many segments did you drag before you saw this?

**Comment by tsortwehttam** [comment]
Further info: The the reason scaling effect isn't appearing on-stage - despite it being correctly set -
 is because the 2.5D layout algorithm incorporates all the transform components as part of one big algebra calculation. With rotation.z undefined, the scale output ends up munged in the transformation matrix too. Basically, cascading failures - with the root cause being `rotation.z` getting set to `undefined` (`NaN` in the view) for an unknown reason.

**Comment by taylorpoe** [comment]
> How much timeline zoom did you have?

Was working at 100% entire time

> How fast did you drag the segment? Did you drag from its body or an edge?

Fast originally, then slow to put it exactly on the desired frame. Dragged from the body as much as possible since my durations were already what I wanted them to be. I haven't seen this bug before and I don't often drag from the body, so I imagine this might be a good place to look.

> Any error in the script console or among the toasts?

No, there were no errors.

> How many segments did you drag before you saw this?

I dragged all of the star elements' (~6) segments about ~9 per star before playing the timeline and seeing no animation.
